### ISSUE TITLE
`scope` type is incompatible with @aws-cdk/core@^1.83.0

### ISSUE THREAD

**Issue by seanWLawrence** [awslabs/aws-solutions-constructs#116]
`Types have separate declarations of a private property 'host'.` occurs when trying to instantiate the `CloudFrontToS3` construct

### Reproduction Steps

```typescript
import * as cdk from '@aws-cdk/core';
import * as awsSolutions from '@aws-solutions-constructs/aws-cloudfront-s3';

export class Construct extends cdk.Construct {
  constructor(scope: cdk.Construct, id: string) {
    super(scope, id);

    new awsSolutions.CloudFrontToS3(
      this // TypeScript error,
      'CloudFrontToS3',
      {}
    );
  }
}

```

### Error Log

```bash
Argument of type 'this' is not assignable to parameter of type 'Construct'.

Type 'import("/<path>/api.construct").Construct' is not assignable to type 'import("/<path>/node_modules/@aws-cdk/aws-cloudfront/node_modules/@aws-cdk/core/lib/construct-compat").Construct'.
    Types of property 'node' are incompatible.
      Type 'import("/<path>/node_modules/@aws-cdk/core/lib/construct-compat").ConstructNode' is not assignable to type 'import("/<path>/node_modules/@aws-cdk/aws-cloudfront/node_modules/@aws-cdk/core/lib/construct-compat").ConstructNode'.
        Types have separate declarations of a private property 'host'.ts(2345)
```

### Environment

  - **CDK CLI Version   1.79.0   :**
  - **CDK Framework Version:** ^1.83.0
  - **AWS Solutions Constructs Version  ^1.79.0   :**
  - **OS           Mac 10.15.7        :**
  - **Language     TypeScript        :**

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
seanWLawrence@ This is due to conflicting versions of AWS CDK and AWS Solutions Constructs packages in package.json. Unfortunately using Caret (^) in package.json pulls in the latest major version of the package, which in this case is 1.83.0 for AWS CDK package -vs- 1.79.0 for AWS Solutions Constructs package, which is causing this error.

If you pin the version for AWS CDK package to be same as AWS Solutions Constructs package i.e. "1.79.0" it will resolve the issue.

For example,

```
"@aws-cdk/core": "1.79.0",
"@aws-solutions-constructs/aws-apigateway-dynamodb": "1.79.0",
```

**Comment by hnishar** [comment]
v1.83.0 of `@aws-solutions-constructs/...` modules are now published and can be used with `@aws-cdk/...` modules of the same version
