### ISSUE TITLE
Updating constructs lib causes deploy failure with SqsToLambda DLQ

### ISSUE THREAD

**Issue by station70-jason** [awslabs/aws-solutions-constructs#1176]
When using SqsToLambda construct, upgrading from 2.58.1 to 2.60+ results in a failure to deploy due to conflicting resources.

This seems to be caused by the change to https://github.com/awslabs/aws-solutions-constructs/blame/main/source/patterns/%40aws-solutions-constructs/core/lib/sqs-helper.ts#L226

changing the line in `source/patterns/@aws-solutions-constructs/core/lib/sqs-helper.ts`
from
`const buildQueueResponse = buildQueue(scope, 'deadLetterQueue', {`
to
`const buildQueueResponse = buildQueue(scope, `${id}-dlq`, {`

in PR #1131

### Reproduction Steps

In CDK stack
```py
sample = SqsToLambda(
            self,
            "Sample",
            lambda_function_props=_lambda.FunctionProps(...),
                handler="sample.handler",
            ),
            queue_props=sqs.QueueProps(
                queue_name=f"sample",
                removal_policy=RemovalPolicy.DESTROY,
            ),
            dead_letter_queue_props=sqs.QueueProps(
                queue_name=f"sample_dlq",
                removal_policy=RemovalPolicy.DESTROY,
            ),
)
```

Deploy with older version of constructs (< 2.60), update constructs version (>= 2.60), then attempt re-deploy.

### Error Log

On `cdk deploy`:
```
$STACK_NAME | 4:28:23 PM | CREATE_FAILED        | AWS::SQS::Queue                 | $CONSTRUCT_ID/queue-dlq ($CONSTRUCT_IDqueuedlq2DA5CD76) Resource handler returned message: "Resource of type 'AWS::SQS::Queue' with identifier '$DLQ_QUEUE_NAME' already exists." (RequestToken: 6c1eae2c-5e34-3e13-eaf1-f1ed356f727d, HandlerErrorCode: AlreadyExists)
```

`cdk diff` shows queue name changes, from `SampledeadLetterQueueABCD1234` to `SamplequeuedlqEFGH5678` which correlates with the change I highlighted above.

### Environment

  - **CDK CLI Version      : 2.152**
  - **CDK Framework Version: 2.150.0**
  - **AWS Solutions Constructs Version     : 2.65.0**
  - **OS                   : MacOS 14.6.1/Ubuntu 22.04**
  - **Language             : Python**

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks, we'll take a look

**Comment by biffgaut** [comment]
The problem is the combination of the new version changing the resource ID and your code using hardcoded resource names. The resource name change results in the the resource being replaced. Apparently CloudFormation creates the new resource before deleting the old resource - so it  is  trying to create the replacement queue while the original queue still exists. Since the queue has a name defined in the code, both the original and replacement queues have the same name and can't exist simultaneously, causing the error you see.

I can see two paths forward for you.

1) Remove the queue name from your code and allow CDK/Cloudformation to generate the name. They will create names that are unique to each stack and reproducible. Delegating naming resources to CDK/CFN is really highly recommended as it makes environments less brittle. For instance, I believe that if  you tried to launch your app twice in the same region you would see an error when the two application installations collide at the queue name. If the queue name is to integrate with other apps, it can be specified as an output so other stacks can reference it.

2) If it is not feasible to remove the hardcoded queue name, you can change the name of the dlq and successfully launch. If the name must remain "sample-dlq" (or whatever value is in your actual code), you can

- Change the name in the code
- Launch with the new version of Constructs
- Change the name back to the original in the code
- Launch (Update) the stack again

I tried that process here and ended up with the same name on the queue.

**Comment by station70-jason** [comment]
@biffgaut Thanks for the advice on workarounds. We can certainly use one of those strategies in our circumstances. 

I'm concerned that this change wasn't called out in release notes for potential data loss. I believe the resource ID change would cause old DLQs to be replaced, losing any messages that might have been sitting in them.

**Comment by station70-jason** [comment]
To be more precise, anyone who had a DLQ built with this Construct prior to 2.60 would lose all messages in those DLQs upon deploying after upgrading to 2.60+ because the change in #1131 changed the resource IDs of all those queues.

**Comment by biffgaut** [comment]
That's a good point - we'll dig into it further and look at updating CHANGELOG.md

**Comment by biffgaut** [comment]
Yes, an existing DLQ will be deleted along with any messages - we will update the CHANGELOG accordingly.

Eventually someone reading this Issue may ask, why did we make this change? We needed to do it when we added a Construct Factory for SQS queues. Since the original code had a fixed resource ID for DLQs, when we created Queues outside of a Solutions Construct we see ID collisions if an app deployed 2 queues. This code would not work:

```
    const factories = new ConstructsFactories(this, 'factories');
    factories.sqsQueueFactory('this-queue', {});
    factories.sqsQueueFactory('that-queue', {});
```

If you haven't looked at Constructs Factories yet, you should check them out - we're very excited about them. We haven't really publicized them yet - we're aiming for a blog post this Fall.

**Comment by biffgaut** [comment]
CHANLGELOG.md. has been updated. We think this completes this Issue and will close it in a couple weeks unless we hear otherwise.  If you're good, you can close it now if you like.

**Comment by station70-jason** [comment]
I appreciate all the explanation, and the push towards these factories does sound like an improvement. I'll definitely need to look through and learn more about them. Thanks for all the work the team is doing, it makes my job a lot easier. 😄
