### ISSUE TITLE
aws-cloudfront-s3 README issue and cannot generate OAI resource

### ISSUE THREAD

**Issue by JoeShi** [awslabs/aws-solutions-constructs#127]
1. The README documentation of aws-cloudfront-s3 pattern is not correct.
2. The pattern did not create OAI anymore. I remember in early version, it do create the CloudFront OAI. Example can be seen [here](https://github.com/awslabs/serverless-image-handler/blob/c5db6f7efbd6d151c31f2781c9a6c3c3c9d7d299/source/constructs/lib/serverless-image-handler.ts#L424).

### Reproduction Steps

In the [documentation](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/patterns/%40aws-solutions-constructs/aws-cloudfront-s3) here. The type of `cloudFrontDistributionProps` is `cloudfront.CloudFrontWebDistributionProps`. However, in the [code](https://github.com/awslabs/aws-solutions-constructs/blob/5ebdc41501b418454555c00b492e16866ae3be44/source/patterns/%40aws-solutions-constructs/aws-cloudfront-s3/lib/index.ts#L41), it is `cloudfront.DistributionProps`.

### Error Log

No.

### Environment

  - **CDK CLI Version      :**
  - **CDK Framework Version:**
  - **AWS Solutions Constructs Version     :**
  - **OS                   :**
  - **Language             :**

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks - we'll take a look and see what's going on.

**Comment by hnishar** [comment]
Thanks for the feedback. Since v1.68.0, for all Cloudfront patterns, the underlying Cloudfront L2 CDK construct has changed from [CloudFrontWebDistribution](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CloudFrontWebDistribution.html) to [Distribution](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.Distribution.html) See the [Changelog](https://github.com/awslabs/aws-solutions-constructs/blob/master/CHANGELOG.md#1680-2020-10-16) and related [issue](https://github.com/awslabs/aws-solutions-constructs/issues/39) We will update the READMEs

**Comment by hnishar** [comment]
One of the benefits of using the new L2 CDK construct was that it creates the OAI hence the `aws-cloudfront-s3` pattern no longer needs to create the OAI, so if you change your input props from [CloudFrontWebDistributionProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.CloudFrontWebDistributionProps.html) to [DistributionProps](https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-cloudfront.DistributionProps.html) you should see the OAI resource being created.

**Comment by hnishar** [comment]
JoeShi@ Documentation has been updated to reflect the updated Pattern Construct Props for aws-cloudfront-s3 pattern

https://docs.aws.amazon.com/solutions/latest/constructs/aws-cloudfront-s3.html#pattern-construct-props-5
