### ISSUE TITLE
Guidance on Higher Level Abstractions (Use Cases)

### ISSUE THREAD

**Issue by maria-jackson** [awslabs/aws-solutions-constructs#131]
From [sample use cases](https://github.com/awslabs/aws-solutions-constructs#sample-use-cases), 
> These can be used in the same way as architectural patterns, and can be conceptualized as an additional "higher-level" abstraction of those patterns.

It appears AWS's intention is for companies to contribute to aws-cdk and aws-soultions-contructs. If a company needs a higher level abstraction with reusability, would that be a good enterprise library for a company? I can import the other two, but I need to copy and paste the third from AWS. 

[aws-serverless-image-handler](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/use_cases/aws-serverless-image-handler) is what I'd imagine a "higher level" abstraction that could be shared would look like. It follows "The client should have the option (but not requirement) to provide any props used within the construct", but doesn't fit with "Constructs should be decomposed to their smallest architecture" [design guidelines](https://github.com/awslabs/aws-solutions-constructs/blob/master/DESIGN_GUIDELINES.md).

Did notice that the [readme](https://github.com/awslabs/aws-solutions-constructs/tree/master/source/use_cases/aws-serverless-image-handler#aws-serverless-image-handler) actually lists this as an aws-solutions-constructs pattern. (it isn't)

```
const { ServerlessImageHandler } from '@aws-solutions-constructs/aws-serverless-image-handler';
```

### Use Case

Ex. I recently needed a "SNS to SQS to Lambda to Secret" for some alerting infrastructure. I see my team and my company using an identical pattern in 100's of apps. (or as foundational elements in 100 accounts)

Ex. Pre-CDK tech like Elastic Beanstalk translated more directly into CDK

I think there will be a lot more patterns like this. This is too complex for an aws-solutions-constructs pattern, but definitely looks like a use case. 

If our developers are using aws-solutions-constructs well (and contributing back), I hope the majority of their time coding infrastructure will be making things that look more like the "use cases." 

### Proposed Solution

More guidance on creating "higher level" abstractions and a better understanding of AWS's intentions for "higher level" abstractions.

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
The code under Use Cases is just meant to be examples of how to use Solutions Constructs to create larger architectures, they are not constructs themselves and are not decomposed  to their smallest architecture. The Serverless Image Handler is actually a clone of an older version of the full AWS Solution Serverless Image Handler. The import code you cite in the README appears to be an error (or at least misleading), as the examples are not published to npm - we will look into that.

We certainly encourage customers to make their own higher level constructs, encompassing both L2 CDK constructs and our L3 Solutions Constructs. AWS publishes higher level abstractions through our [AWS Solutions Library](https://aws.amazon.com/solutions/)(many of which are built with Solutions Constructs). Solutions Constructs will continue to focus on small constructs that can be combined in a variety of ways to cover more use cases.

I'm not sure I covered all your questions, please let me know if there are areas that I missed. Thanks.

**Comment by maria-jackson** [comment]
I totally understand that those are examples. 

Internally, we have something similar to the AWS Solutions Library for things that are more specific to our work. It looks almost the same. "Here's a little code and little explanation, copy and paste what you need." What happens when you need to use a specific solution from something like AWS Solutions Library, hundreds of times in a hundred accounts? We are seeing some of those patterns emerge.

One option is a packaged library with things that look a bit like aws-serverless-image-handler. It is definitely a further abstraction than an aws-solutions-constructs construct, but it meets some qualities ("The client should have the option (but not requirement) to provide any props used within the construct") that would help it be more reusable.

AWS Solutions Library may never need to be reusable, but for a specific company, I believe, we will have slightly larger patterns that we use over and over again in different accounts.

Ex. The architect designs a beautiful C4 model. The developer starts looking at the different levels and notices, "This looks like the AWS Solutions Library/Internal Solutions Library example I saw. In fact, I've already done this in 15 other repositories in 15 accounts. Wow, aws-solutions-constructs made that so easy, but I'm still copying and pasting code. I think I'm ready for a higher level component."

What is your guidance for making that sort of library? The kind of advice I'm looking for:
- Don't use "experimental" aws-solutions-constructs (which I assume that they will be stable at some point)
- Just try to follow all the aws-solutions-constructs ideas, except "Constructs should be decomposed to their smallest architecture"
- It's a bad idea, don't do it at all. You've missed X, Y, and Z fundamental ideas!
- I have no idea. We are just focusing on aws-solutions-constructs, try it out and let us know what you think

**Comment by biffgaut** [comment]
The only bullet point for which I can give an iron clad answer is the third one - we think it's a great idea! 

How you design yours is something you will discover over time - the more specific and complete a construct is the less effort it will be to use, but the fewer use cases it will cover. Solutions Constructs explicitly try to be as generic as possible to be useful to the largest audience and to enable composition with multiple constructs to create any architecture you want. The trade-off is that each construct individually only solves "part" of an architecture. That goal wasn't immediately clear to us when we started and you'll notice we have some constructs from early on that don't meet our "smallest architecture" criteria (e.g. aws-lambda-sqs-lambda). 

It sounds like you have already identified some higher level use cases that are repeated in your organization - I'd start with those, see the response they get and refine you guidelines as you go along. Also check out the approach some other Construct libraries out there that others besides AWS are publishing - there's a prominent one [here](https://cdkpatterns.com/).

We launched our library with every construct marked Experimental and basically haven't returned to the issue yet - it comes up often and we're close to moving them all to stable. I can't guarantee that there won't be a breaking change to any we have published so far, but it's very unlikely (and since versions have to be explicitly stated, a new version with a breaking change won't break your build until you upgrade). I think it is very safe to go ahead use the Experimental Solutions Constructs - and I think you'll see them transition to Stable soon.
