### ISSUE TITLE
Upgrade version in parallel to @aws-cdk

### ISSUE THREAD

**Issue by jeromevdl** [awslabs/aws-solutions-constructs#151]
When using the latest version of @aws-cdk (currently 1.94.1), there is an issue with solution constructs are they are based on version 1.93.0 (ex of issue #116). Would be great to automate version update when aws-cdk is updated so we are aligned.

### Use Case

Currently, I cannot use the latest version of aws-cdk if I want to use solution-constructs, because of version mismatch.

### Proposed Solution

Leverage https://github.com/aws-cdk-automation to automate both repos

### Other

* [ ] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

This is a :rocket: Feature Request

**Comment by askulkarni2** [comment]
This would be really useful. Something like https://github.com/projen/projen with GitHub actions can be used to keep this repo in sync with CDK releases.

**Comment by biffgaut** [comment]
Thanks for the feedback. The requirement that all libraries must be in sync also trips us up internally as well. Because of this requirement, we generally stay one release behind the CDK so that if a major bug is uncovered we have the ability to quickly release an update. 

The upcoming CDK 2.0 release should eliminate this issue - our current plan is to wait for CDK 2.0 rather than expend resources addressing a situation with an imminent end date.
