### ISSUE TITLE
aws-kinesisstream-gluejob: Can't create multiple Jobs in the same stack

### ISSUE THREAD

**Issue by FinnIckler** [awslabs/aws-solutions-constructs#199]
It's not possible to two Streaming Jobs, as Glue Policy has a hard-coded name and can not be created twice. This could be fixed by appending the construct name to the Glue Policy name

### Reproduction Steps

```
streaming_job = KinesisstreamsToGluejob(self, "streaming-job", glue_job_props={"command": {
            "name": "gluestreaming",
            "pythonVersion": "3",
            "scriptLocation": assets.Asset(self, "SparkCode", path="spark_code/transform.py").s3_object_url,
        }}, field_schema=SCHEMA, existing_stream_obj=input_data_stream)

streaming_job_2 = KinesisstreamsToGluejob(self, "streaming-job2", glue_job_props={"command": {
    "name": "gluestreaming",
    "pythonVersion": "3",
    "scriptLocation": assets.Asset(self, "SparkCode2", path="spark_code/maps.py").s3_object_url,
}}, existing_table=streaming_job.table, existing_database=streaming_job.database,
                                        existing_stream_obj=input_data_stream)
```

### Error Log

`jsii.errors.JSIIError: There is already a Construct with name 'GlueJobPolicy' in Construct`

### Environment

  - **CDK CLI Version      :1.104
  - **CDK Framework Version:1.104
  - **AWS Solutions Constructs Version     :1.104
  - **OS                   :MacOs
  - **Language             :Python

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Pretty sure the issue is here-

https://github.com/awslabs/aws-solutions-constructs/blob/fcd9d3075260a826da75d5a9b633457b7fee6517/source/patterns/%40aws-solutions-constructs/aws-kinesisstreams-gluejob/lib/index.ts#L172

Consider creating the name like this:

https://github.com/awslabs/aws-solutions-constructs/blob/fcd9d3075260a826da75d5a9b633457b7fee6517/source/patterns/%40aws-solutions-constructs/aws-s3-step-function/lib/index.ts#L150
