### ISSUE TITLE
Lambda to EventBus construct

### ISSUE THREAD

**Issue by nirweiner2** [awslabs/aws-solutions-constructs#344]
Hi.
I would love to have a feature that adds lambda the functionality to write to an event bus.
Even though it is super simple I think it should be done as it is similar to LambdaToSQS construct in its idea.
What do you think?

This is a :rocket: Feature Request

**Comment by biffgaut** [comment]
Thanks, we'll take a look

**Comment by nirweiner2** [comment]
I may have misunderstood you because as far as I understand you can interact with non-default event bus.
`    const eventbus1 = new EventBus(this, 'eventbus1', {eventBusName: "eventbus1"})`
Then, you can use this eventbus to grant permission for publishing events:
`eventbus1.grantPutEventsTo(my_lambda)`
And then, you would also want to send the event bus name as a variable to that lambda:
`  my_lambda.addEnvironment('EVENTBUS_NAME', eventbus1.eventBusName)`
That could all be done with a constract such as "lambdaToEventBus(this, my_lambda, eventbus1)`

**Comment by biffgaut** [comment]
I agree that it can be done in the CDK, but the construct interface for EventBridge currently does not support the concept of non-default event busses.  One of our tenets is that services work consistently across all constructs - e.g. once someone understands how the SQS-Lambda construct defines and implements a Lambda function, then they also understand how Lambda functions are defined for S3-Lambda, SNS-Lambda, etc.

So the interface defined in DESIGN_GUIDELINES.md will need to be updated to include EventBusProps, ExistingEventBus; plus exposing the EventBus as a property. Then all the EventBridge constructs will need to be updated to support this functionality.

We agree it is a worthy goal, but our limited resources are committed elsewhere right now so it's on our backlog until we can tackle it.

**Comment by biffgaut** [comment]
Since leaving the above comment, we have an internal volunteer to work on this. Depending upon the bandwidth they can devote to the task, it may be coming sooner than originally thought. We're going to start with updating the existing constructs to use non-default event buses, as the interaction with targets and rules will make them more complicated that this construct as we figure out the interface design.

**Comment by biffgaut** [comment]
We started with adding custom event bus functionality to the existing EventBridge constructs - the last release included custom event bus features on aws-eventbridge-lambda. Our thought was that because they deal with rules and targets they would be more complex than lambda-eventbridge when defining the changes to the interface. The others are in progress and we should be implementing aws-eventbridge-lambda after these.

**Comment by surukonda** [comment]
@biffgaut please close this

**Comment by biffgaut** [comment]
Closed with [368](https://github.com/awslabs/aws-solutions-constructs/pull/368)

**Comment by biffgaut** [comment]
(this is in the GitHub repo and will be pushed out to NPM, PyPi, etc. this weekend.
