### ISSUE TITLE
LoggingBucket fails to empty on destroy even if autoDeleteObjects is passed to bucketProps

### ISSUE THREAD

**Issue by ruggero-visintin** [awslabs/aws-solutions-constructs#394]
Using autoDeleteObjects with buildS3Bucket fails on destroying due to loggingBucket not been emptied

### Reproduction Steps

This is the code that creates the bucket
```typescript
const [supportBucket] = solutions.buildS3Bucket(this, {
  bucketProps: {
    removalPolicy: cdk.RemovalPolicy.DESTROY,
    autoDeleteObjects: true
  },
}, 'SupportBucket');
```

### Error Log

The bucket you tried to delete is not empty. You must delete all versions in the bucket. (Service: Amazon S3; Status Code: 409; Error Code: BucketNotEmpty; Request ID: Q3DTRYVFC6K80GRV; S3 Extended Request ID: jUNX7KdHXU65qvaCIMCUVWEHXe4clm5JYRYDaOpEuSbAXgfv1oVlXdJEFfdlZvDInCuQLbrFYuM=; Proxy: null)

### Environment

  - **CDK CLI Version      :** 1.114.0
  - **CDK Framework Version:** --
  - **AWS Solutions Constructs Version     :** 1.114.0
  - **OS                   :** MacOS
  - **Language             :** typescript

### Other

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
That's the CloudFormation behavior with regard to buckets - it's very difficult to delete buckets with versioning turned on, it can only be done via the [console, SDK or REST API](https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html)(not the CLI nor CloudFormation). This is intentional, as versioning is a recommended practice to prevent loss of accidentally or maliciously deleted objects. For dev and test environments where buckets are created and destroyed more dynamically and without production data, one solution may be to include `versioned: false` in your bucket props.

It may be possible to write a custom resource in CloudFormation to clean out the versions, we'll convert this to a feature request on our backlog to gauge support for such a feature.

**Comment by ruggero-visintin** [comment]
Sorry, maybe I wasn't clear enough. The main bucket it's emptied and deleted successfully thanks to the autoDeleteObjects policy that does exactly what you said, that wasn't possible some time ago. 

The bucket that isn't deleted is the loggingBucket created by default from the `solutions.buildS3Bucket` method. The main bucket is deleted successfully even if versioning is enabled

**Comment by ruggero-visintin** [comment]
This has been better explained [here](https://github.com/awslabs/aws-solutions-constructs/issues/213#issuecomment-898726106).

Basically only the `removalPolicy` is passed to the loggingBucket construction but the `autoDeleteObjects` property isn't considered

**Comment by biffgaut** [comment]
Ah - OK. We've got an In Progress issue that will allow clients to specify props for logging buckets [here](https://github.com/awslabs/aws-solutions-constructs/issues/213). This will allow you to customize the logging bucket however you like. Watch for this to roll out across constructs with S3 buckets over the rest of this year.

**Comment by ruggero-visintin** [comment]
> buckets

Thanks for the support!

**Comment by biffgaut** [comment]
We're rolling this out across constructs now - any particular construct that you would like us to do sooner than later?

**Comment by biffgaut** [comment]
We've added the ability to control logging buckets across all constructs. This update should allow you to specify props for the logging bucket that allow you to define the behavior you want.
