### ISSUE TITLE
New Pattern: cloud9-ec2-ssm

### ISSUE THREAD

**Issue by bpguasch** [awslabs/aws-solutions-constructs#495]
When launching a Cloud9 EC2 environment you have no flexibility in configuring the Block Devices that are attached to it and you can't either pass a UserData script to apply an initial configuration (i.e: installing dependencies). By default, a Cloud9 EC2 environment has an EBS volume of 10GB, which runs short in most of the cases.

### Use case

Many customers use Cloud9 for running workshops and immersion days. Only in the Spot domain, 70% them run into the issue described above and have to manually resize the EBS volume and install the dependencies, what abstracts them from the purpose of those sessions. Furthermore, those customers that use Cloud9 as their IDE run into the same issue when, for instance, building a docker image and they don't have an automated way to solve it.

### Proposed solution

Automated resizing of EBS volume and dependencies installation in Cloud9 EC2 environments by:

1. Deploy a Cloud9 EC2 environment
2. Create an SSM document
3. Create an SSM document association to apply the configuration to the EC2 instance

### Other

- [✅] I may be able to implement this pattern

**Comment by biffgaut** [comment]
Thanks, we'll take a look.

**Comment by biffgaut** [comment]
Most members of our team love Cloud9 and use it whenever we need a pristine dev environment, and we all love what this solution would provide. That said, it doesn't meet the philosophy of Solutions Constructs - it's more of a solution than a minimal building block that can be used to build larger architectures. I'm going to close this issue here - but I understand you may be publishing this in another manner. If so, please come back to this issue and post a link so that we and others can find it.

**Comment by bpguasch** [comment]
It's been published here: https://github.com/aws-samples/cdk-use-cases/tree/main/use_cases/custom-cloud9-ssm
