### ISSUE TITLE
(aws-cloudfront-s3):  cloudFrontDistributionProps autocomplete is not populating

### ISSUE THREAD

**Issue by robertd** [awslabs/aws-solutions-constructs#5]
cloudFrontDistributionProps autocomplete is not populating

![image](https://user-images.githubusercontent.com/31543/85458032-e95d1900-b55d-11ea-93b2-17325793d5aa.png)

### Reproduction Steps

```ts
import * as acs3 from '@aws-solutions-constructs/aws-cloudfront-s3';

new acs3.CloudFrontToS3(this, "test", {
      deployBucket: true,
      cloudFrontDistributionProps: {
        
      },
      bucketProps: {
        bucketName: "test"
      },
    });

```

### Environment

  - **CDK CLI Version      :** 1.46.0
  - **CDK Framework Version:** 1.46.0
  - **AWS Solutions Constructs Version     :** 1.46.0
  - **OS                   :** MacOS
  - **Language             :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by robertd** [comment]
When I try to override the property...
![image](https://user-images.githubusercontent.com/31543/85465136-ab63f300-b565-11ea-8ac6-10dc38a52905.png)

I'm getting a warning:

`WARN AWS_SOLUTIONS_CONSTRUCTS_WARNING:  An override has been provided for the property: undefined.`

**Comment by GerardKetuma** [comment]
There is a bug in the s3-bucket-helper function s3BucketWithLogging on the following line:
https://github.com/awslabs/aws-solutions-constructs/blob/078015520d248d80a8e1697aa0a86b3eedea8c3e/source/patterns/%40aws-solutions-constructs/core/lib/s3-bucket-helper.ts#L70

Currently it is:
`bucketprops = DefaultS3Props;`

But it should be:
`bucketprops = DefaultS3Props();` as DefaultS3Props is a function that returns an object and bucketprops should be an object.

I'm creating a PR to resolve the issue.

**Comment by hnishar** [comment]
robertd@ the PR has been merged and that should fix the override warning message.. 

Regarding the autocomplete issue, `CloudFrontToS3Props` has `cloudFrontDistributionProps` declared as `cloudfront.CloudFrontWebDistributionProps | any`.. due to the `any` type the IDE is probably not doing the autocomplete.. the `any` type is required otherwise the caller will need to set the mandatory `originConfigs` property of S3 bucket that is yet to be created by the pattern
