### ISSUE TITLE
DefaultS3Props with new Lifecycle Policy produces errors when versioning overridden

### ISSUE THREAD

**Issue by mobri2a** [awslabs/aws-solutions-constructs#80]
Creating BucketProps from core Defaults3Props, then modifying to suit: disable versioning. Causes an error: Cannot use 'noncurrent' rules on a nonversioned bucket. It appears that a default lifecycle policy was added in 1.64.0. For customers that may have used the example code below prior to 1.64.0, this will cause their stack to fail.

### Reproduction Steps

```
let bucketprops = DefaultS3Props();

ArtifactBucketCfg = overrideProps(ArtifactBucketCfg, {
    serverAccessLogsPrefix: 'access-logs',
    versioned: false
})

const bktArtifact = new s3.Bucket(this, "ArtifactBucket");
```

### Error Log

Cannot use 'noncurrent' rules on a nonversioned bucket

### Environment

  - **CDK CLI Version      :** 1.64.0
  - **CDK Framework Version:** 1.64.0
  - **AWS Solutions Constructs Version     :** 1.64.0
  - **OS                   :** OS/X
  - **Language             :** Typescript

### Other

--- 

This is :bug: Bug Report

**Comment by hnishar** [comment]
mobri2a@ Good find! The fix has been pushed out in the latest release v1.64.1, for proof see [this](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/core/test/s3-bucket-helper.test.ts#L214) test case with versioning `disabled` which does not have the default life cycle policy and [this](https://github.com/awslabs/aws-solutions-constructs/blob/master/source/patterns/%40aws-solutions-constructs/core/test/s3-bucket-helper.test.ts#L249) test case with default versioning `enabled` which has the default life cycle policy.

For future reference, we do *not* recommend using the default props directly from the `core` package in the application code unless absolutely necessary. In which case, be aware to use the build function, if available. For instance, in this case, use [buildS3Bucket](https://github.com/awslabs/aws-solutions-constructs/blob/e15714d06a22a1bcbc871ff63f2efddfe52b277e/source/patterns/%40aws-solutions-constructs/core/lib/s3-bucket-helper.ts#L31) function instead of [DefaultS3Props](https://github.com/awslabs/aws-solutions-constructs/blob/e15714d06a22a1bcbc871ff63f2efddfe52b277e/source/patterns/%40aws-solutions-constructs/core/lib/s3-bucket-defaults.ts#L18)
