### ISSUE TITLE
[aws-kinesisstreams-lambda]: Unable to use existing Kinesis Stream

### ISSUE THREAD

**Issue by i906** [awslabs/aws-solutions-constructs#889]
### Reproduction Steps

```ts
// returns kinesis.IStream
const existingStreamObj = kinesis.Stream.fromStreamArn(this, 'stream', 'arn:aws:kinesis:ap-southeast-1:000000000000/stream/existing-stream');

new KinesisStreamsToLambda(this, 'job-kinesis-trigger', {
      existingLambdaObj,
      existingStreamObj, // wants kinesis.Stream
      kinesisEventSourceProps: {}
});
```

### Error Log

```
TS2740: Type 'IStream' is missing the following properties from type 'Stream': stream, parseEncryption, metricFromCannedFunction, physicalName, and 6 more.
```

### Environment

  - **CDK CLI Version      : 2.61.0**
  - **CDK Framework Version: 2.61.0**
  - **AWS Solutions Constructs Version     : 2.30.0**
  - **OS                   : macOS Ventura**
  - **Language             : Typescript**

### Other

Related issues: https://github.com/awslabs/aws-solutions-constructs/issues/58, https://github.com/awslabs/aws-solutions-constructs/pull/60

--- 

This is :bug: Bug Report

**Comment by biffgaut** [comment]
Thanks for the note. Right now, everything is working as documented - although perhaps we can/should change the implementation. The CDK Stream.fromStreamArn is documented to return an IStream object, presumably because it is the Stream class's implementation of IStream's method. While a Stream object can be passed as an IStream, an IStream can't be passed as a Stream (our current prop value).

That said, we may be able to alter the interface so that the props object accepts IStream for existingStream - I took a quick look this morning and it appears that we aren't using any Stream object specific functionality of the existing Stream. We'll change this from bug to change request and look at it a little deeper.
